### ISSUE TITLE
Sphinx Audio processing with Hadoop

### ISSUE THREAD

**Issue by balatextcomputing** [cmusphinx/sphinx4#15]
Hello,

We are testing Sphinx to find text from audio in Hadoop.

is there a way where we can give multiple files (rather than a directory) to setAcousticModelPath 

as seen below

configuration.setAcousticModelPath is expecting a directory and not a file, 

```
        configuration.setAcousticModelPath("./wsj_8kHz233/wsj_8kHz233/wsj_8kHz11111");
```

Please help

**Comment by gupash** [comment]
Hi All,

I am a little late to the party :)
I am currently doing the same stuff, converting wav files to text using hadoop/spark.
I have 1 question for you @balatextcomputing, were you able to split the audio wav file across input splits and do parallel processing in mappers. Thats the only benefit of using hadoop here, otherwise the file processing can be done in normal java program also, if it has to be sequential.

I couldn't find a way to split the wav file or process the wav file in splitted/byte array form by sphinx library.

waiting for your reply..
Thanks in advance
